### PR TITLE
Breaking change. Update to AndroidX

### PR DESCRIPTION
**Pull request by I-am-original**
Hi there. Here is I have tried to update to AndroidX. Please take a look on it. As many libs already updated. It is like a Flash mob from Google ) Cheers

### CODE REVIEW

**Comment by I-am-original** [comment]
@miguelpruivo Please check my MR ) I have updated my commit. So for now it should contain only stuff related to update to AndroidX.
All other stuff - like lib/generated and android/.idea was removed from commit. As actually .idea/ should not be there as for me.
Cheers :)

**Comment by miguelpruivo** [comment]
May I ask you why you found this PR useful? I mean, it's been working fine with api 27, any particular reason that made you change to 28? 

Thank you.

**Comment by I-am-original** [comment]
All google's flutter plugins have mighated to AndroidX, so we should also
migrate to it. But I cant migrate on my own. All libs should migrate.


сб, 26 січ. 2019, 23:03 Miguel Ruivo користувач notifications@github.com
пише:

**Comment by miguelpruivo** [comment]
Right, but was it working fine with 27 too right? I'll take a look into it.

**Comment by I-am-original** [comment]
@miguelpruivo done )

**Comment by miguelpruivo** [comment]
Merged to `beta`. Thank you.

**Comment by I-am-original** [comment]
@miguelpruivo thanks ) we have common cause )

**Pull request merged**
