### PR TITLE
Add file_picker Go support.

### PR DESCRIPTION
**Pull request by GeertJohan**
Originally written by @chunhunghan, squashed, cleaned up and fixed for MacOS

### CODE REVIEW

**Comment by miguelpruivo** [comment]
Does this replace the other open PR at all? Thank you.

**Comment by GeertJohan** [comment]
@miguelpruivo Yes

**Comment by GeertJohan** [comment]
I found another small bug on MacOS, which has been fixed and force-pushed to this branch. All should be good to go now :)

**Comment by miguelpruivo** [comment]
Would you mind to change it to the `beta` please? Thank you.

**Comment by GeertJohan** [comment]
DOne

**Comment by GeertJohan** [comment]
This does make it hard to use from Go, as it by default checks the master branch. The default usage instructions don't apply as long as it's only in the beta branch.

**Comment by miguelpruivo** [comment]
@GeertJohan what do you mean? It will soon be merged to `master` but I just want to run some tests on my machine before merging and releasing a new version with Go. Could you please add me on Skype (ruivom), I would like to discuss with you some points.

Thank you.

**Comment by Drakirus** [comment]
There is a little mistake in the go/readme.md and the wiki:
The import line should be:
```
	file_picker "github.com/miguelpruivo/plugins_flutter_file_picker/go"
```
instead of 
```
	"github.com/miguelpruivo/plugins_flutter_file_picker/go"
```

**Comment by miguelpruivo** [comment]
Corrected. Thank you for pointing out @Drakirus!

**Comment by Drakirus** [comment]
You're welcome 😊.
(just to make sure the wiki has been updated but https://github.com/miguelpruivo/flutter_file_picker/blob/master/go/README.md still shows the wrong import, I'm guessing you're on you can't commit atm)

**Comment by miguelpruivo** [comment]
@Drakirus didn't want to commit on `master` right now, but never mind, done it. 🙂

**Pull request merged**
