### PR TITLE
Migrated to AndroidX

### PR DESCRIPTION
**Pull request by sarbagyastha**

### CODE REVIEW

**Comment by miguelpruivo** [comment]
Thank you for combruting but this was already done on `beta`.

**Comment by sarbagyastha** [comment]
@miguelpruivo When will you publish new version on Pub then ?

**Comment by miguelpruivo** [comment]
@sarbagyastha soon. I'm looking to release a new version with a few improvements & suggestions.

**Comment by miguelpruivo** [comment]
Version 1.2.0 is already on Pub with Android X changes that were already in `beta`. Closing this PR. Thank you.

**Pull request closed without merging**
