### PR TITLE
beta branch add go-flutter desktop support

### PR DESCRIPTION
**Pull request by chunhunghan**
add folder go-desktop with 9 files to beta branch.

Code review and related discussion
https://github.com/go-flutter-desktop/go-flutter/issues/205#

### CODE REVIEW

**Comment by Drakirus** [comment]
In the go-desktop/README.md file you can update the `[application options]` link to `https://github.com/go-flutter-desktop/go-flutter/wiki/Plugin-info` instead of the old example.

**Comment by Drakirus** [comment]
Once this PR gets merged, user will have to manually run:
```
go get -u github.com/miguelpruivo/plugins_flutter_file_picker/go-desktop@beta
``` 
in the `desktop` directory of their 'hover' project.

Once beta gets merged into master, everything will be handled by hover.

**Comment by miguelpruivo** [comment]
@Drakirus I've installed `hover` on my Mac machine and I'm trying to run a sample project just to test it out, however, I'm always getting the `hover: command not found` when I try to init it.

Am I missing something?

**Comment by Drakirus** [comment]
@miguelpruivo what's the output of
`go get -u github.com/go-flutter-desktop/hover`? 

Did you set your [GOPATH] (https://github.com/golang/go/wiki/Gopath) correctly?

**Comment by miguelpruivo** [comment]
@Drakirus there’s not output at all. However, I haven’t set the path, so that might be it.

I’ll set it whenever I get back to it and then see if I can make it work.

**Comment by miguelpruivo** [comment]
@Drakirus I'm still having the same issue. Looks like I can't get the `hover` to work. How are you setting the `GOPATH`?

**Comment by Drakirus** [comment]
go get probably installed it to `~/go/bin`. Please check if its there, then add that folder to your `PATH`

**Comment by GeertJohan** [comment]
I have taken the liberty to create #132, which squashes all the commits in this PR and fixes use for MacOS. It also uses the new directory structure for go compatibility code in plugins. (See go-flutter-desktop/go-flutter#209)

**Comment by miguelpruivo** [comment]
I'm closing this because #132 is already merged. Thank you for contributing!

**Pull request closed without merging**
